version: '3'
services:
  r-ver-devel:
    image: g4challenge/r-ver:devel
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_r-ver_devel
  rstudio-devel:
    image: g4challenge/rstudio:devel
    depends_on:
    - r-ver-devel
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_rstudio_devel
  tidyverse-devel:
    image: g4challenge/tidyverse:devel
    depends_on:
    - rstudio-devel
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_tidyverse_devel
  verse-devel:
    image: g4challenge/verse:devel
    depends_on:
    - tidyverse-devel
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_verse_devel
