version: '3'
services:
  r-ver-4.0.4:
    image: g4challenge/r-ver:4.0.4
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_r-ver_4.0.4
  rstudio-4.0.4:
    image: g4challenge/rstudio:4.0.4
    depends_on:
    - r-ver-4.0.4
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_rstudio_4.0.4
  tidyverse-4.0.4:
    image: g4challenge/tidyverse:4.0.4
    depends_on:
    - rstudio-4.0.4
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_tidyverse_4.0.4
  verse-4.0.4:
    image: g4challenge/verse:4.0.4
    depends_on:
    - tidyverse-4.0.4
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_verse_4.0.4
