version: '3'
services:
  r-ver-4.0.4-cuda11.1:
    image: g4challenge/r-ver:4.0.4-cuda11.1
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_r-ver_4.0.4-cuda11.1
  ml-4.0.4-cuda11.1:
    image: g4challenge/ml:4.0.4-cuda11.1
    depends_on:
    - r-ver-4.0.4-cuda11.1
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_ml_4.0.4-cuda11.1
  ml-verse-4.0.4-cuda11.1:
    image: g4challenge/ml-verse:4.0.4-cuda11.1
    depends_on:
    - ml-4.0.4-cuda11.1
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_ml-verse_4.0.4-cuda11.1
