version: '3'
services:
  r-ver-devel-cuda10.1:
    image: g4challenge/r-ver:devel-cuda10.1
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_r-ver_devel-cuda10.1
  ml-devel-cuda10.1:
    image: g4challenge/ml:devel-cuda10.1
    depends_on:
    - r-ver-devel-cuda10.1
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_ml_devel-cuda10.1
  ml-verse-devel-cuda10.1:
    image: g4challenge/ml-verse:devel-cuda10.1
    depends_on:
    - ml-devel-cuda10.1
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_ml-verse_devel-cuda10.1
  ml-devel:
    image: g4challenge/ml:devel
    depends_on:
    - ml-verse-devel-cuda10.1
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_ml_devel
  ml-verse-devel:
    image: g4challenge/ml-verse:devel
    depends_on:
    - ml-devel
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_ml-verse_devel
