version: '3'
services:
  shiny-4.0.3:
    image: g4challenge/shiny:4.0.3
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_shiny_4.0.3
  shiny-verse-4.0.3:
    image: g4challenge/shiny-verse:4.0.3
    depends_on:
    - shiny-4.0.3
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_shiny-verse_4.0.3
